### ISSUE TITLE
bitstream library missing

### ISSUE THREAD

**Issue by danielsreichenbach** [aarondl/mpq#1]
Hi,

just wanted to try out the mpq package, and it seems the bitstream package required is missing.

Any chance you can make that available too?

WkR,
Daniel

**Comment by aarondl** [comment]
Hi Daniel.

Absolute I will push that. Seems silly to have forgotten it. The only problem is it's stuck on my desktop which is unplugged while I'm in another country for the week. Next week I will get this pushed!

Sorry for the inconvenience!

**Comment by aarondl** [comment]
Should be fixed.
